[package]
name = "audmedia_linux"
version = "0.1.0"
edition = "2021"
authors = ["AUDmedia Team"]
description = "Lightweight Linux mobile-style music player"
license = "MIT"

[dependencies]
gtk4 = { version = "0.9", features = ["v4_10"] }
libadwaita = "0.7"
gstreamer = "0.23"
walkdir = "2.5.0"
lofty = "0.25.1"
rand = "0.8.5"
image = "0.25.10"
sha2 = "0.11.0"
